language: rust
rust:
  - stable
  - beta
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo
  - cargo test